#!/bin/bash
# Olympix Claude Plugin — Interactive Setup Wizard
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PARENT_DIR="$(cd "$PLUGIN_DIR/.." && pwd)"
ENV_FILE="$PLUGIN_DIR/.env"

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

echo ""
echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  Olympix Claude Plugin Setup Wizard${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# ─── Step 1: Check Prerequisites ───

echo -e "${GREEN}Step 1: Check Prerequisites${NC}"
echo ""

# Check Olympix CLI
if command -v olympix &>/dev/null; then
    OLYMPIX_VERSION=$(olympix --version 2>/dev/null || echo "unknown")
    echo -e "  ${GREEN}[installed]${NC} olympix CLI ($OLYMPIX_VERSION)"
elif [ -x "$HOME/.opix/bin/olympix" ]; then
    OLYMPIX_VERSION=$("$HOME/.opix/bin/olympix" --version 2>/dev/null || echo "unknown")
    echo -e "  ${GREEN}[installed]${NC} olympix CLI ($OLYMPIX_VERSION) at ~/.opix/bin/olympix"
else
    echo -e "  ${YELLOW}[not installed]${NC} olympix CLI"
    echo -e "  Install from: ${CYAN}https://docs.olympix.ai/cli${NC}"
fi

# Check Forge
if command -v forge &>/dev/null; then
    FORGE_VERSION=$(forge --version 2>/dev/null | head -1 || echo "unknown")
    echo -e "  ${GREEN}[installed]${NC} forge ($FORGE_VERSION)"
else
    echo -e "  ${YELLOW}[not installed]${NC} forge (Foundry)"
    echo -e "  Install from: ${CYAN}https://getfoundry.sh${NC}"
fi

echo ""

# ─── Step 2: Optional Email Configuration ───

echo -e "${GREEN}Step 2: Email Configuration (optional)${NC}"
echo ""
echo "  Your Olympix account email is used for auth convenience."
echo "  Leave empty to skip."
echo ""
read -p "  Olympix email: " OLYMPIX_EMAIL
OLYMPIX_EMAIL="${OLYMPIX_EMAIL:-}"

cat > "$ENV_FILE" << ENVEOF
# Olympix Claude Plugin — Generated by setup.sh on $(date +%Y-%m-%d)

# Your Olympix account email (optional, used for auth convenience)
OLYMPIX_EMAIL=$OLYMPIX_EMAIL
ENVEOF

echo -e "  ${GREEN}OK${NC} — .env written to $ENV_FILE"
echo ""

# ─── Step 3: Register Plugin with Claude Code ───

echo -e "${GREEN}Step 3: Plugin Registration${NC}"
echo ""

# Determine install scope
echo "  Where should the plugin be registered?"
echo ""
echo "    1. Global    — all projects (~/.claude/settings.json)"
echo "    2. Workspace — this workspace only (.claude/settings.local.json)"
echo ""
read -p "  Choice [2]: " INSTALL_SCOPE
case ${INSTALL_SCOPE:-2} in
    1) INSTALL_MODE="global" ;;
    2) INSTALL_MODE="workspace" ;;
    *) INSTALL_MODE="workspace" ;;
esac
echo -e "  ${GREEN}OK${NC} — $INSTALL_MODE install"
echo ""

# Check that claude CLI is available
if ! command -v claude &>/dev/null; then
    echo -e "  ${RED}ERROR${NC} — 'claude' CLI not found in PATH."
    echo "  Install Claude Code first: https://docs.anthropic.com/en/docs/claude-code/overview"
    exit 1
fi

# Determine install scope flag
if [ "$INSTALL_MODE" = "global" ]; then
    SCOPE_FLAG="--scope user"
else
    SCOPE_FLAG="--scope local"
fi

# Step 3a: Ensure marketplace manifest exists at parent directory
MARKETPLACE_DIR="$PARENT_DIR"
MARKETPLACE_MANIFEST="$MARKETPLACE_DIR/.claude-plugin/marketplace.json"

if [ -f "$MARKETPLACE_MANIFEST" ]; then
    # Marketplace manifest already exists — add our plugin entry if not present
    if command -v jq &>/dev/null; then
        if ! jq -e '.plugins[] | select(.name == "olympix-claude-plugin")' "$MARKETPLACE_MANIFEST" &>/dev/null; then
            tmp_file=$(mktemp)
            jq '.plugins += [{
                "name": "olympix-claude-plugin",
                "description": "Run Olympix smart contract security tools from Claude Code — static analysis, mutation tests, fuzz tests, unit tests, and BugPocer exploit generation",
                "source": "./olympix-claude-plugin",
                "category": "development"
            }]' "$MARKETPLACE_MANIFEST" > "$tmp_file" && mv "$tmp_file" "$MARKETPLACE_MANIFEST"
            echo -e "  ${GREEN}OK${NC} — added olympix-claude-plugin to existing marketplace manifest"
        else
            echo -e "  ${GREEN}OK${NC} — olympix-claude-plugin already in marketplace manifest"
        fi
    else
        echo -e "  ${YELLOW}WARN${NC} — jq not installed, cannot merge into existing marketplace manifest"
        echo "  Manually add olympix-claude-plugin entry to $MARKETPLACE_MANIFEST"
    fi
else
    echo -e "  Creating marketplace manifest..."
    mkdir -p "$MARKETPLACE_DIR/.claude-plugin"
    cat > "$MARKETPLACE_MANIFEST" << 'MKJSON'
{
  "$schema": "https://anthropic.com/claude-code/marketplace.schema.json",
  "name": "olympix",
  "description": "Olympix Claude Code plugins for smart contract security",
  "owner": {
    "name": "Olympix",
    "email": "engineering@olympix.ai"
  },
  "plugins": [
    {
      "name": "olympix-claude-plugin",
      "description": "Run Olympix smart contract security tools from Claude Code — static analysis, mutation tests, fuzz tests, unit tests, and BugPocer exploit generation",
      "source": "./olympix-claude-plugin",
      "category": "development"
    }
  ]
}
MKJSON
    echo -e "  ${GREEN}OK${NC} — marketplace manifest created at $MARKETPLACE_MANIFEST"
fi

# Step 3b: Register marketplace
echo -e "  Registering marketplace..."
if claude plugins marketplace list 2>/dev/null | grep -q "olympix"; then
    echo -e "  ${GREEN}OK${NC} — marketplace 'olympix' already registered"
else
    if claude plugins marketplace add "$MARKETPLACE_DIR" 2>&1; then
        echo -e "  ${GREEN}OK${NC} — marketplace 'olympix' registered"
    else
        echo -e "  ${RED}FAIL${NC} — could not register marketplace"
        echo "  Try manually: claude plugins marketplace add $MARKETPLACE_DIR"
        exit 1
    fi
fi

# Step 3c: Install plugin
echo -e "  Installing plugin..."
if claude plugins list 2>/dev/null | grep -q "olympix-claude-plugin@olympix"; then
    echo -e "  ${GREEN}OK${NC} — olympix-claude-plugin already installed"
else
    if claude plugins install olympix-claude-plugin@olympix $SCOPE_FLAG 2>&1; then
        echo -e "  ${GREEN}OK${NC} — olympix-claude-plugin installed ($INSTALL_MODE)"
    else
        echo -e "  ${RED}FAIL${NC} — could not install plugin"
        echo "  Try manually: claude plugins install olympix-claude-plugin@olympix $SCOPE_FLAG"
        exit 1
    fi
fi

# Step 3d: Add Olympix CLI permissions to settings
echo "  Adding Olympix CLI to Claude Code allowed commands..."

if [ "$INSTALL_MODE" = "global" ]; then
    SETTINGS_FILE="$HOME/.claude/settings.json"
else
    SETTINGS_FILE="$PARENT_DIR/.claude/settings.local.json"
fi

OLYMPIX_PERMISSIONS=(
    'Bash(olympix:*)'
    'Bash(forge coverage:*)'
    'Bash(forge build:*)'
    'Bash(forge test:*)'
    'Bash(forge install:*)'
    'Bash(npm install:*)'
)

if command -v jq &>/dev/null && [ -f "$SETTINGS_FILE" ]; then
    ADDED=0
    for perm in "${OLYMPIX_PERMISSIONS[@]}"; do
        if ! jq -e --arg p "$perm" '.permissions.allow | index($p)' "$SETTINGS_FILE" &>/dev/null; then
            tmp_file=$(mktemp)
            jq --arg p "$perm" '.permissions.allow += [$p]' "$SETTINGS_FILE" > "$tmp_file" && mv "$tmp_file" "$SETTINGS_FILE"
            ADDED=$((ADDED + 1))
        fi
    done
    if [ "$ADDED" -gt 0 ]; then
        echo -e "  ${GREEN}OK${NC} — added $ADDED permission(s) to $(basename "$SETTINGS_FILE")"
    else
        echo -e "  ${GREEN}OK${NC} — all permissions already present"
    fi
elif command -v jq &>/dev/null && [ ! -f "$SETTINGS_FILE" ]; then
    mkdir -p "$(dirname "$SETTINGS_FILE")"
    PERM_JSON=$(printf '%s\n' "${OLYMPIX_PERMISSIONS[@]}" | jq -R . | jq -s .)
    jq -n --argjson perms "$PERM_JSON" '{"permissions": {"allow": $perms}}' > "$SETTINGS_FILE"
    echo -e "  ${GREEN}OK${NC} — created $(basename "$SETTINGS_FILE") with Olympix permissions"
else
    echo -e "  ${YELLOW}WARN${NC} — jq not installed, cannot update settings automatically"
    echo "  Manually add these to $SETTINGS_FILE under permissions.allow:"
    for perm in "${OLYMPIX_PERMISSIONS[@]}"; do
        echo "    \"$perm\""
    done
fi

echo ""

# ─── Step 4: Success ───

echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  Setup Complete!${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""
echo "Restart Claude Code to activate the plugin."
echo ""
echo -e "${GREEN}Quick start:${NC}"
echo "  Open Claude Code in a Foundry project and run:"
echo -e "  ${CYAN}/olympix:full-run${NC}"
echo ""
echo "Available skills:"
echo "  olympix:full-run          — Run all Olympix tools on a Foundry repo"
echo "  olympix:static-analysis   — Run vulnerability scanner"
echo "  olympix:mutation-test     — Generate mutation tests for top 10 contracts"
echo "  olympix:fuzz-test         — Generate fuzz tests for top 3 contracts"
echo "  olympix:unit-test         — Generate unit tests with coverage scaffolding"
echo "  olympix:bug-pocer         — Launch BugPocer interactive security analysis"
echo "  olympix:assemble-report   — Collect results into olympix-results/report.md"
echo "  olympix:auth              — Check/refresh CLI authentication"
echo ""
echo -e "${YELLOW}Recommended: Connect Gmail MCP for the full experience${NC}"
echo ""
echo "  The Olympix skills can automate login (reading verification codes)"
echo "  and monitor async results (mutation/fuzz/unit tests) via Gmail."
echo ""
echo "  To connect: run /mcp in Claude Code and connect 'claude.ai Gmail'"
echo ""
echo "  Without Gmail MCP, these features fall back to manual:"
echo "    - Login: you enter the verification code yourself"
echo "    - Results: you check email and provide metrics"
echo "    - Report assembly: you copy result files manually"
echo ""
